### ISSUE TITLE
Feather Icons' Missing

### ISSUE THREAD

**Issue by kevinchristianto** [WrathChaos/react-native-dynamic-vector-icons#19]
I couldn't find Feather Icon in your library, while Feather Icon is listed in README

**Comment by WrathChaos** [comment]
@kevinchristianto Thank you so much! I do not know how to miss it :( I will add it today :)

**Comment by WrathChaos** [comment]
Hey again @kevinchristianto, I've released a new version: [1.0.0](https://github.com/WrathChaos/react-native-dynamic-vector-icons/releases/tag/1.0.0)

Please check this out :)

**Comment by kevinchristianto** [comment]
Whoa, thanks dude!
