### ISSUE TITLE
Typed icon names

### ISSUE THREAD

**Issue by davidgovea** [WrathChaos/react-native-dynamic-vector-icons#29]
It would be awesome to type the icon names for each font.

Came upon this library after getting burned by the Ionicons5 upgrade while using `native-base`'s `<Icon>` component (somewhat similar to this library). "unlock" changed to "lock-open", etc.

I'm trying to move away from native-base, so thanks for this lib!

**Comment by WrathChaos** [comment]
Hello @davidgovea,
Thank you for using this library :) 

I can make the typed icon names ASAP.

**Comment by WrathChaos** [comment]
I will make every one of them with typed support after the new release @davidgovea  :) Probably today

**Comment by davidgovea** [comment]
So.. I gave this some thought and made an initial attempt.

### Challenges:
* Different versions of RNVI have different glyph sets. Since this library brings it in as a peerDep, how can the consuming project be "in control"?
* We can expect RNVI to update their glyphs again in the future. Creating/updating the types should be easy.

**Given these constraints, I used `recast` and took an AST-generation approach.**

1. TypeScript creates the "basic" `Icon.d.ts` file, like it is today
2. The generator script reads the glyphmaps from RNVI, and "injects" the `names` into the existing typedef file's IconProps declarations

This approach would allow consuming projects to run the generator themselves (perhaps in a `postinstall` hook) to match the types to their installed version of RNVI (I have not fully tested this behavior yet -- just the in-repo generation for npm publishing)

So, the idea is that this library ships with up-to-date type definitions, but users can opt-in to generating their own typedef.

Initial WIP PR here: https://github.com/davidgovea/react-native-dynamic-vector-icons/pull/4

See build CI action: https://github.com/davidgovea/react-native-dynamic-vector-icons/runs/1142517766?check_suite_focus=true

It works! The example App.tsx file now errors if a non-existent icon `name` is used for a given font `type`. :+1: 

### Downsides:
* The `Icon.d.ts` file is now `275kB` :scream: (open the "examine archive" section of the CI run above)
  * Won't add build size, but I wonder if it could slow down the typescript code server?

I've been quite interested in this "postinstall type generation" pattern for some other work in [react-native-tailwindcss](https://github.com/TVke/react-native-tailwindcss) as well (which uses per-project config files to customize the resultant styles). Looking to experiment more & discover any pain points
