### ISSUE TITLE
FontAwesome5

### ISSUE THREAD

**Issue by davidgovea** [WrathChaos/react-native-dynamic-vector-icons#30]
The README lists FontAwesome5, but it is not present in code.

I've noticed that similar Icon utilities, like that of `natve-base` and `react-native-elements` also don't include FA5, or have added it and then reverted. 

I suspect that including it caused issues for users, but not sure what.
Maybe the font loading? ..looks like FA5Pro is separate though, and ttfs [are preset](https://github.com/oblador/react-native-vector-icons/tree/master/Fonts).
Maybe its the [additional props](https://github.com/oblador/react-native-vector-icons/blob/master/FONTAWESOME5.md#usage) adding complexity?

**Comment by WrathChaos** [comment]
This issue solved thanks to @davidgovea.
Here is the new release: 

## [New Release: 1.1.3 🥳](https://github.com/WrathChaos/react-native-dynamic-vector-icons/releases/tag/1.1.3)
