### ISSUE TITLE
Cannot read property "cache" of undefined

### ISSUE THREAD

**Issue by smooJitter** [WrathChaos/react-native-dynamic-vector-icons#9]
I am getting an error node_modules/react-native-dynamic-vector-icons/lib/components/Icon.tsx: Cannot read property 'cache' of undefined.

Please advise

**Comment by WrathChaos** [comment]
Hello @smooJitter,
Can you show me the error? There is literally no 'cache' variable or anything in the `Icon.tsx`. Are you trying to use it in the Expo project? Also, If it is possible please share me a reproducible example :)

**Comment by smooJitter** [comment]
Exactly...  I tried to find it.  I'll take a closer look, especially considering you don't get this error in your set up.  Note, I am running on a device under debug.

**Comment by WrathChaos** [comment]
I'm using this library more than 20+ projects :) I could not reproduce this issue, can you share with me a reproducible example? Then, I can fix it.
